repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.12.3
    hooks:
      - id: check-autopkg-recipe-list
      - id: check-autopkg-recipes
      - id: forbid-autopkg-trust-info
